[phases.setup]
nixPkgs = ["nodejs_18", "openssl"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@10.33.2 --activate",
  "pnpm i --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm --filter @workspace/api-server run start"
